[package]
name = "rexx-rules"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rexx-diagnostics = { path = "../rexx-diagnostics" }
rexx-config = { path = "../rexx-config" }
rexx-ast = { path = "../rexx-ast" }
rexx-parser = { path = "../rexx-parser" }
rexx-lexer = { path = "../rexx-lexer" }

[dev-dependencies]
insta = "1"
rexx-analyzer = { path = "../rexx-analyzer" }
