[package]
name = "rexx-walker"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bench]]
name = "walker"
harness = false
path = "../../benches/walker.rs"

[dependencies]
ignore.workspace = true
walkdir.workspace = true
globset.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
criterion.workspace = true
